name: Release

permissions:
  contents: write
  id-token: write

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Install pnpm
        uses: pnpm/action-setup@v3
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Login to NPM
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Setup
        run: npm i -g @antfu/ni release-it @release-it/conventional-changelog changelogithub should-semantic-release
      - name: Install
        run: nci
      - run: if should-semantic-release --verbose ; then release-it --verbose && changelogithub ; fi
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
