name: Release

permissions:
  contents: write
  id-token: write

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          - name: Install pnpm
          uses: pnpm/action-setup@v3
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Setup
        run: npm i -g @antfu/ni
      - name: Install
        run: nci
      - run: nr release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
